import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { makeServer } from './serve.mjs';
import { external } from './external.mjs';
const { chromium } = await external('playwright', '1.58.2', 'PLAYWRIGHT_PACKAGE');
const server = makeServer(); await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
let browser;
try {
  browser = await chromium.launch({ headless: true, ...(process.env.BROWSER_EXECUTABLE ? { executablePath: process.env.BROWSER_EXECUTABLE } : {}) });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto(`http://127.0.0.1:${server.address().port}`);
  assert.equal(await page.title(), 'LotGate · Auction Lab');
  assert.equal(await page.textContent('h1'), 'LotGate.');
  await page.waitForFunction(() => document.getElementById('orders').value.includes('buyer-A'));
  await page.click('#init'); await page.click('#step'); assert.equal(await page.textContent('#volume'), '300');
  assert.equal(await page.locator('#orders').isDisabled(), true);
  await page.click('#run'); await page.waitForFunction(() => document.getElementById('state').textContent === 'Đã kết thúc');
  assert.equal(await page.textContent('#volume'), '1200'); assert.equal(await page.textContent('#price'), '10');
  assert.ok((await page.textContent('#status')).includes('oracle'));
  const downloadPromise = page.waitForEvent('download'); await page.click('#export'); const download = await downloadPromise; assert.equal(download.suggestedFilename(), 'LotGate-report.json');
  await mkdir(new URL('../reports/', import.meta.url), { recursive: true });
  await page.screenshot({ path: fileURLToPath(new URL('../reports/desktop.png', import.meta.url)), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.screenshot({ path: fileURLToPath(new URL('../reports/mobile.png', import.meta.url)), fullPage: true });
  await page.click('#reset'); await page.fill('#orders', '[{"id":"bad","side":"buy","price":"0","quantity":"1"}]'); await page.click('#init');
  assert.ok((await page.textContent('#status')).includes('Positive'));
  assert.deepEqual(errors, []); console.log('Browser PASS: step/run, lock config, verified result, export, mobile layout, invalid order, no page errors.');
} finally { await browser?.close(); await new Promise(resolve => server.close(resolve)); }
