import assert from 'node:assert/strict';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { external } from './external.mjs';
import { Session, sortedBook, normalize } from '../src/session.mjs';
import { json } from '../src/auction.mjs';
const solc = await external('solc', '0.8.30', 'SOLC_PACKAGE');
const ganache = await external('ganache', '7.9.2', 'GANACHE_PACKAGE');
const sources = {};
for (const name of ['AuctionSandbox', 'NandBenchmark']) sources[`${name}.sol`] = { content: await readFile(new URL(`../contracts/${name}.sol`, import.meta.url), 'utf8') };
const compiled = JSON.parse(solc.compile(JSON.stringify({ language: 'Solidity', sources, settings: { optimizer: { enabled: true, runs: 200 }, evmVersion: 'shanghai', outputSelection: { '*': { '*': ['abi', 'evm.bytecode.object', 'evm.methodIdentifiers'] } } } })));
assert.deepEqual((compiled.errors ?? []).filter(e => e.severity === 'error'), []);
const provider = ganache.provider({ logging: { quiet: true }, chain: { hardfork: 'shanghai', chainId: 1337 }, miner: { blockGasLimit: 100000000 }, wallet: { totalAccounts: 3 } });
const request = (method, params = []) => provider.request({ method, params });
const word = n => BigInt(n).toString(16).padStart(64, '0');
const words = hex => (hex.slice(2).match(/.{64}/g) ?? []).map(w => BigInt(`0x${w}`));
const artifact = name => compiled.contracts[`${name}.sol`][name];
const encode = (name, signature, args = []) => `0x${artifact(name).evm.methodIdentifiers[signature]}${args.map(word).join('')}`;
const report = { scope: 'Ephemeral Ganache Shanghai EVM; virtual credits only; NAND interpreter is NOT TapeOut CPU.', compiler: solc.version(), optimizerRuns: 200, gas: {} };
try {
  const [owner, other] = await request('eth_accounts');
  const send = async (to, data, from = owner) => {
    const hash = await request('eth_sendTransaction', [{ from, ...(to ? { to } : {}), data, gas: '0x5f5e100' }]);
    const receipt = await request('eth_getTransactionReceipt', [hash]); assert.equal(receipt.status, '0x1'); return receipt;
  };
  const deploy = async (name, args = []) => send(null, `0x${artifact(name).evm.bytecode.object}${args.map(word).join('')}`);
  const deployment = await deploy('AuctionSandbox', [25, 0]), address = deployment.contractAddress;
  report.gas.deploySandbox = BigInt(deployment.gasUsed);
  const call = (signature, args = [], from = owner) => request('eth_call', [{ from, to: address, data: encode('AuctionSandbox', signature, args) }, 'latest']);
  const tx = (signature, args = [], from = owner) => send(address, encode('AuctionSandbox', signature, args), from);
  const reject = async (signature, args = [], from = owner) => assert.rejects(call(signature, args, from));
  await tx('faucet()'); await tx('faucet()', [], other); await reject('faucet()'); await reject('settle()');
  const book = JSON.parse(await readFile(new URL('../examples/orders.json', import.meta.url)));
  for (const o of book) await tx('submit(bool,uint32,uint32)', [o.side === 'buy' ? 1 : 0, o.price, o.quantity], o.side === 'buy' ? owner : other);
  const lists = sortedBook(normalize(book).rows).map(rows => rows.map(r => r.priority));
  const commitData = (b, s) => `0x${artifact('AuctionSandbox').evm.methodIdentifiers['commit(uint256[],uint256[])']}${word(64)}${word(96 + b.length * 32)}${word(b.length)}${b.map(word).join('')}${word(s.length)}${s.map(word).join('')}`;
  for (const [b, s] of [[[0, 0], [2, 3, 4]], [[1, 0], [2, 3, 4]], [[0], [2, 3, 4]], [[0, 2], [1, 3, 4]]]) await assert.rejects(request('eth_call', [{ from: owner, to: address, data: commitData(b, s) }, 'latest']));
  await assert.rejects(request('eth_call', [{ from: other, to: address, data: commitData(...lists) }, 'latest']));
  report.gas.commit = BigInt((await send(address, commitData(...lists))).gasUsed);
  await reject('submit(bool,uint32,uint32)', [1, 10, 1]); await reject('settle()');
  report.gas.matchSession = BigInt((await tx('step(uint256)', [64])).gasUsed);
  await reject('step(uint256)', [1]);
  const expected = new Session(book, { feeBps: 25 }).run();
  assert.equal(words(await call('volume()'))[0], expected.volume); assert.equal(words(await call('clearingPrice()'))[0], expected.clearingPrice);
  for (let i = 0; i < book.length; i++) assert.equal(words(await call('orders(uint256)', [i]))[4], expected.allocations[i].filled);
  report.gas.settle = BigInt((await tx('settle()')).gasUsed); await reject('settle()');
  assert.equal(words(await call('totalFees()'))[0], expected.totalFees);
  assert.equal(words(await call('base(address)', [BigInt(owner)]))[0], (1n << 100n) + expected.volume);
  assert.equal(words(await call('quote(address)', [BigInt(owner)]))[0], (1n << 100n) - expected.volume * expected.clearingPrice + expected.totalFees);
  assert.equal(words(await call('base(address)', [BigInt(other)]))[0], (1n << 100n) - expected.volume);
  assert.equal(words(await call('quote(address)', [BigInt(other)]))[0], (1n << 100n) + expected.volume * expected.clearingPrice - expected.totalFees);
  const direct = encode('AuctionSandbox', 'directMatch(uint32,uint32,uint32,uint32)', [12, 10, 1000, 300]);
  assert.deepEqual(words(await request('eth_call', [{ to: address, data: direct }, 'latest'])), [1n, 300n, 700n, 0n]);
  report.gas.directPair = BigInt((await send(address, direct)).gasUsed);
  const nand = (await deploy('NandBenchmark')).contractAddress;
  const net = (await readFile(new URL('../circuits/modular/sub32.netlist.hex', import.meta.url), 'utf8')).trim().slice(2);
  const input = Buffer.alloc(8); [1000, 300].forEach((v, i) => input.writeUInt32LE(v, i * 4));
  const dynamic = hex => word(hex.length / 2) + hex.padEnd(Math.ceil(hex.length / 64) * 64, '0');
  const data = `0x${artifact('NandBenchmark').evm.methodIdentifiers['evaluate(bytes,bytes,uint256,uint256)']}${word(128)}${word(128 + dynamic(net).length / 2)}${word(64)}${word(33)}${dynamic(net)}${dynamic(input.toString('hex'))}`;
  const output = await request('eth_call', [{ to: nand, data, gas: '0x5f5e100' }, 'latest']);
  const bytes = Buffer.from(output.slice(130, 140), 'hex');
  const bitword = (start, width) => { let n = 0n; for (let i = 0; i < width; i++) n |= BigInt((bytes[(start+i)>>3] >> ((start+i)&7)) & 1) << BigInt(i); return n; };
  assert.deepEqual([bitword(0,32),bitword(32,1)], [700n,0n]);
  report.gas.nandSub32CalldataInterpreter = BigInt((await send(nand, data)).gasUsed);
  await mkdir(new URL('../reports/', import.meta.url), { recursive: true });
  await writeFile(new URL('../reports/evm.json', import.meta.url), json(report) + '\n'); console.log(json(report));
} finally { await provider.disconnect(); }
